[tools]
darklua = "seaofvoices/darklua@0.15.0"
wally-package-types = "johnnymorganz/wally-package-types@1.4.2"
wally = "UpliftGames/wally@0.3.2"
rojo = "rojo-rbx/rojo@7.4.4"
stylua = "johnnymorganz/stylua@2.0.2"
selene = "kampfkarren/selene@0.28.0"
luau-lsp = "johnnymorganz/luau-lsp@1.38.1"
