[tools]
wally-package-types = "johnnymorganz/wally-package-types@1.6.2"
wally = "UpliftGames/wally@0.3.2"
rojo = "rojo-rbx/rojo@7.5.1"
stylua = "johnnymorganz/stylua@2.3.0"
selene = "kampfkarren/selene@0.29.0"
luau-lsp = "johnnymorganz/luau-lsp@1.54.0"
