[package]
name = "herfave/roblox-project-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
# General purpose
Comm = "sleitnick/comm@1.0.1"
Signal = "sleitnick/signal@2.0.1"
Janitor = "howmanysmall/janitor@1.16.0"
TableUtil = "sleitnick/table-util@1.2.1"
Promise = "evaera/promise@4.0.0"
WaitFor = "sleitnick/wait-for@^0.2.1"
Timer = "sleitnick/timer@^1.1.2"
EnumList = "sleitnick/enum-list@*"
Input = "sleitnick/input@^2.3.0"
Sift = "csqrl/sift@0.0.9"
ObjectCache = "pyseph/objectcache@1.4.4"
Iris = "sirmallard/iris@2.3.1"

# React dependencies
Fusion = "elttob/fusion@0.3.0"

# Reflex = "littensy/reflex@^4.3.1"
# ReactReflex = "littensy/react-reflex@^0.3.5"

[server-dependencies]
Lyra = "paradoxum-games/lyra@0.6.0"