[package]
name = "herfave/roblox-project-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# General purpose
Comm = "sleitnick/comm@1.0.1"
Signal = "sleitnick/signal@2.0.1"
Janitor = "howmanysmall/janitor@1.16.0"
TableUtil = "sleitnick/table-util@1.2.1"
Promise = "evaera/promise@4.0.0"
WaitFor = "sleitnick/wait-for@^0.2.1"
Timer = "sleitnick/timer@^1.1.2"
EnumList = "sleitnick/enum-list@*"
Input = "sleitnick/input@^2.3.0"
Sift = "csqrl/sift@0.0.9"
ObjectCache = "pyseph/objectcache@1.4.4"
Iris = "sirmallard/iris@2.3.1"

# React dependencies
React = "jsdotlua/react@^17.0.2"
ReactRoblox = "jsdotlua/react-roblox@^17.0.2"
Ripple = "littensy/ripple@0.9.2"
ReactErrorBoundary = "chriscerie/react-error-boundary@^0.2.0"
RoactTemplate = "corecii/roact-template@^0.2.0"
Charm = "littensy/charm@^0.9.0"
ReactCharm = "littensy/react-charm@0.2.0"
CharmSync = "littensy/charm-sync@0.2.0"

# Reflex = "littensy/reflex@^4.3.1"
# ReactReflex = "littensy/react-reflex@^0.3.5"

[server-dependencies]
DataKeep = "noahrepublic/datakeep@5.0.0"
