-- create a ball
-- allow players to return the ball
-- left click speeds up the ball, direct return
-- right click slows down, creates a bigger arc, but can change the angle

-- rackets influence base stats
-- innate ability (spirits)
-- ultimate abilities (awakenings)

local RallyService = {}

-- calculate trajectory
function RallyService:BallHit(initialLocation, angle)
	-- playback path
end

return RallyService
